### ISSUE TITLE
Does this still work on iOS 8.1?

### ISSUE THREAD

**Issue by robertoandrade** [tolo/HHServices#13]
Trying to run the samples on both my iPhone and Simulator and then checking either via Bonjour Browser or using the Browser sample doesn't yield any results. Any ideas?

**Comment by robertoandrade** [comment]
I noticed when switching back and forth to the Publisher sample app, the following log message appears:

```
2015-03-16 14:50:01.298 PublisherSample[273:18475] HHServicePublisher[MyDisplayName, _myexampleservice._tcp., local.] - Error: -65563
```

When searching for that error code it looks like it's returned when mDNSResponder daemon isn't running? How's that possible?

**Comment by tolo** [comment]
Hi, as far as I know everything should still work - this is used in apps available on the app store (PlayMyQ for instance). And I just re-tested PlayMyQ to make sure that this still works there :)

I also tried running the publisher sample on an iPhone, running iOS8.2, and the browser sample in the simulator (Xcode 6.2), and it seemed to work fine for me at least. What exact os versions / xcode version are you using? 

Note that the publisher app needs to be in the "foreground" when running on a device, for the publishing to work/be active. Also, note that publishing/browsing via bluetooth doesn't work when running in the simulator.

**Comment by tolo** [comment]
Closing this for now - please re-open if it seems this is an issue with HHServices.
