### ISSUE TITLE
iOS9 not resolving address from iOS10

### ISSUE THREAD

**Issue by sgosztyla** [tolo/HHServices#17]
I tried out the iOS10 beta recently and noticed that HHServices no longer resolves bluetooth addresses on the iOS9 side. I drilled down and it looks like DNSServiceGetAddrInfo never calls the callback after beginning to resolve an address from getNextAddressInfo. ~~I haven't tried it with two iOS10 devices yet, but I have a hunch it will work fine.~~ 

~~I noticed almost the same exact issue when iOS8 came out, were it would only work with other iOS8 versions. With iOS9 it again worked with every version other than 8.~~

Any ideas how to solve this would be great. ~~Pretty worried this is an iOS issue and I won't be able to do anything about it, and using the iOS Multipeer framework is just too slow for my needs.~~

**Comment by tolo** [comment]
I haven't tried HHServices with iOS10 beta yet, but I'm going to try and do that soon. In the mean time, please have a look at the develop branch and see if that works better (it includes some general improvements as well as a few minor bug fixes).

**Comment by sgosztyla** [comment]
Thanks Tobias, I haven't looked at the develop branch yet, I'll give that a try. 

I spent some more time looking into the issue and now I'm pretty certain it has to do with iOS enforcing iPv6 addresses for bluetooth. I'm not able to resolve any iOS10 device over bluetooth using HHServices. I tried passing kDNSServiceProtocol_IPv4 | kDNSServiceProtocol_IPv6 into DNSServiceGetAddrInfo in HHService.m to get back an IPv6 address, and resolution did actually return something. The problem was that I couldn't get a usable address out of it.

Hopefully that helps.

**Comment by sgosztyla** [comment]
Hey Tobias,

I was able to fix the issue after adding IPv6 support to my local pull of the main branch!

I tried the develop branch and it also worked after one change:

Make sure to pass kDNSServiceProtocol_IPv4 | kDNSServiceProtocol_IPv6 into the protocol field of DNSServiceGetAddrInfo  in getNextAddressInfo of HHServices.m. Otherwise it won't resolve IPv6 addresses coming from iOS10 devices over Bluetooth.

It should be pretty easy to update the main branch to support IPv6 and close this issue. The develop branch was giving me some latency I wasn't experiencing on the main so I'll stick with that one for now.

Thanks!

**Comment by tolo** [comment]
Hey,

Yeah, I noticed that was missing as well just the other day :) Have added
it locally, will push that change momentarily.
What kind of latency did you experience, and in what operation?

Thanks,
Tobias

**Comment by xaphod** [comment]
Hey help! All of my apps on the app store are gonna be broken, I think because of this exact issue -- the symptom is that iOS 10 won't connect to iOS 9. @sgosztyla can you please please please share your fork of this repo with the fixes?!

**Comment by sgosztyla** [comment]
@tolo, sorry for the delay, I didn't notice the response.

I went back and tested it with the latest develop branch and I'm not seeing any latency. It's possible I left debug logs on, or did something else to cause my slowdowns. Sorry for the false alarm.

**Comment by xaphod** [comment]
@tolo ahh bless you, I was stuck for hours trying to get the updated pod to integrate. Gave up and went for a shower, got back, and you'd fixed it (4:28pm local time here). You are the best

**Comment by tolo** [comment]
Haha, thanks @xaphod ;)

No worries @sgosztyla - glad it works as expected. Also, the develop branch has now been merged into master, and HHServices is now available as a pod.
