### ISSUE TITLE
Still can't integrate HHServices as pod / framework :(

### ISSUE THREAD

**Issue by xaphod** [tolo/HHServices#18]
Hey tolo
No matter what I try, even after your recent commit today I cannot get HHServices to integrate as a framework (via pod) in my apps. I tried a couple different ways, always weird failures. Are you seeing this too?

**Comment by tolo** [comment]
Hey, I've actually just merged the 2.0 changes into master, and I'm in the process of pushing the pod right now, so hopefully it should work in a minute or two :)

**Comment by xaphod** [comment]
OK thanks. I grabbed stuff after your merged 2.0 into master, and added the podspec to my local repo. It builds fine. But when I try to actually use it in an actual app it fails. I'm not sure why. The weird thing: if I alt/option-click the `#include <dns_sd.h>`, it comes up with a blank screen in xcode 8, as if it cannot find it. But only when i'm in another app that is trying to include it and use it...

**Comment by tolo** [comment]
Hmm, that's odd. I just tried adding code to publish a service in a swift project, using the pod now available via cocoapods. It worked both in Xcode7 and Xcode8 (beta 6) for me. Could you try and use the pod from the cocoapods repo and see if that works better?

**Comment by xaphod** [comment]
It still fails. Did you try in xcode 8 to use it (as a pod from master repo) in a swift project?

**Comment by xaphod** [comment]
Actually to be more precise: app --consumes--> bluepeer --requires--> HHServices. So app gets bluepeer and HHServices pods installed, and then HHServices doesn't compile

**Comment by tolo** [comment]
I tried it in a swift project in xcode 8, using the cocoapods repo pod, and it works fine for me...

Where do you get the problems with the dns_sd.h - is it in HHServices or in Bluepeer? Note that I did a change regarding the import of dns_sd.h just recently (so it's no longer being imported from the HHServices-header files.

Or perhaps this is just one of those silly Xcode hiccups - Have you tried cleaning the project and possibly also deleting the DerivedData folder?

**Comment by xaphod** [comment]
It's in HHServices. I tried deleting the DerivedData and *everything* I can think of.
If you tell me your email address i'll email you a sample project?

**Comment by xaphod** [comment]
OK indeed, it was a corruption of my SDK, I believe by the Swift 3 migrator. Apologies to you.

**Comment by tolo** [comment]
Ah, bummer, no worries - glad the problem got resolved! :)
