### ISSUE TITLE
iOS 14 publishing fails

### ISSUE THREAD

**Issue by xaphod** [tolo/HHServices#23]
App has "Always Allowed" Bluetooth access, but I get this when I try to publish a service:

[DEBUG] HHServicePublisher[Tim-s-iPad-Pro-11--4142, _xd-slideshow-1._tcp, local.] - Error: -65555

This DOES repro when building with XCode 12 (release version) on iOS 14.
This does NOT repro when building with XCode 11 on iOS 14.
That makes me think it is some new iOS privacy thing but i'm not sure how to get past it.

Any ideas?

**Comment by xaphod** [comment]
... figured it out. I needed to add two keys to Info.plist:
NSBonjourServices - an array with each of the services the app uses, like _myservicename._tcp / udp
NSLocalNetworkUsageDescription - a string of text explaining to user why local network access is required

**Comment by tolo** [comment]
Great - thanks for investigating and thanks for the info! 😁 
Always fun with all the new info.plist keys in each new iOS-version 😅
