### ISSUE TITLE
[Question] Tips for nonblocking queries?

### ISSUE THREAD

**Issue by lassic** [tolo/HHServices#3]
Hi Tobias,
First, thank you for a great library. It's simple and lean, really awesome.

I've been playing around with trying to make DNSServiceGetAddrInfo nonblocking (as you suggest in the code, I've seen cases it can jam the main thread).
I'm not sure what's the best approach here though, maybe you can help out?
I've tried the GCD approach (since I knew it much better than RunLoops, I'm relatively new to ObjC), dispatching the address resolve query on a global queue and the result back on the main thread.
Since you already have a RunLoop setup, maybe it would be better to use it for the address resolving somehow? I think I might have some issues with locking/canceling the GCD tasks, and perhaps the RunLoop solution will be simpler to handle?

I know about MyNetwork, but I'd rather stick with your library for Bonjour and just add this missing piece. If you could help in pointing in the right direction I'd be grateful.

Thanks again!

**Comment by tolo** [comment]
I'm not sure if this is still an issue, but the development branch anyway contains fixes for a few of the issues mentioned above. Closing this for now (please re-open if there still seems to be issues).
